#!/bin/bash

# helps setting up openvpn for external connections

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

OPENVPN_DIR="/etc/openvpn"
EASYRSA_DIR="/etc/openvpn/easy-rsa"
CLIENT_DIR="/etc/openvpn/clients"
LOG_FILE="/var/log/openvpn-setup.log"
DEFAULT_PORT="1194"
DEFAULT_PROTOCOL="udp"
DEFAULT_SUBNET="10.8.0.0"
DEFAULT_DNS="1.1.1.1"

log() {
    echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1"
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE" 2>/dev/null || true
}

error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
    echo "[ERROR] $1" >> "$LOG_FILE" 2>/dev/null || true
}

warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
    echo "[WARNING] $1" >> "$LOG_FILE" 2>/dev/null || true
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        error "Run script as root"
        exit 1
    fi
}

detect_distro() {
    if [ -f /etc/arch-release ]; then
	DISTRO="arch"
	PKG_MANAGER="pacman"
    elif [ -f /etc/debian_version ]; then
	DISTRO="debian"
	PKG_MANAGER="apt"

	if grep -q "Raspberry Pi" /proc/cpuinfo 2>/dev/null; then
	    IS_RPI=true
	else
	    IS_RPI=false
	fi
    else
	error "Distro not supported yet."
    fi
    
    log "Detected distro: $DISTRO"
    [ "$IS_RPI" = true ] && log "Running on Raspberry Pi"
}

detect_network_interface() {
    DEFAULT_INTERFACE=$(ip route | grep default | awk '{print $5}' | head -n1)

    if [ -z "$DEFAULT_INTERFACE" ]; then
	error "Could not detect default network interface"
	exit 1
    fi

    log "Detected network interface: $DEFAULT_INTERFACE"
    echo "$DEFAULT_INTERFACE"
}

get_public_ip() {
    PUBLIC_IP=$(curl -s ifconfig.me || curl -s icanhazip.com || curl -s ipecho.net/plain)

    if [ -z "$PUBLIC_IP" ]; then
	warning "Couldn't detect public IP"
	read -p "Enter your server's public IP: " PUBLIC_IP
    else
	log "Detected public IP: $PUBLIC_IP"
    fi

    echo "$PUBLIC_IP"
}

install_dependencies() {
    log "Installing required packages..."

    case $PKG_MANAGER in
	pacman)
	    pacman -Sy --noconfirm openvpn easy-rsa qrencode || {
		error "Failed to install packages"
		exit 1
	    }
	    ;;
	apt)
	    apt-get update
	    apt-get install -y openvpn easy-rsa iptables qrencode curl || {
		error "Failed to install packages"
		exit 1
	    }
	    ;;
    esac

    log "Dependencies installed successfully"
}

init_pki() {
    log "Initializing PKI Infastructure"

    mkdir -p "$EASYRSA_DIR"
    mkdir -p "$CLIENT_DIR"

    if [ "$DISTRO" = "arch" ]; then
	cp -r /usr/share/easy-rsa/* "$EASYRSA_DIR/"
    else
	make-cadir "$EASYRSA_DIR"
    fi

    cd "$EASYRSA_DIR"

    ./easyrsa init-pki

    log "Building certificate authority"
    ./easyrsa --batch build-ca nopass

    log "Generating server certificate"
    ./easyrsa --batch build-server-full server nopass

    log "Generating Diffie-Hellman parameters (this may take a while)"
    ./easyrsa gen-dh

    log "Generating TLS authentication key"
    openvpn --genkey secret "$EASYRSA_DIR/pki/ta.key"

    ./easyrsa gen-crl

    cp "$EASYRSA_DIR/pki/ca.crt" "$OPENVPN_DIR/"
    cp "$EASYRSA_DIR/pki/issued/server.crt" "$OPENVPN_DIR/"
    cp "$EASYRSA_DIR/pki/private/server.key" "$OPENVPN_DIR/"
    cp "$EASYRSA_DIR/pki/dh.pem" "$OPENVPN_DIR/"
    cp "$EASYRSA_DIR/pki/ta.key" "$OPENVPN_DIR/"
    cp "$EASYRSA_DIR/pki/crl.pem" "$OPENVPN_DIR/"

    chmod 600 "$OPENVPN_DIR/server.key"
    chmod 600 "$OPENVPN_DIR/ta.key"

    log "PKI initialization complete"
}

generate_client_cert() {
    local CLIENT_NAME="$1"

    if [ -z "$CLIENT_NAME" ]; then
	error "Client name not provided"
	return 1
    fi

    cd "$EASYRSA_DIR"

    if [ -f "pki/issued/${CLIENT_NAME}.crt" ]; then
	error "Client '$CLIENT_NAME' already exists"
	return 1
    fi

    log "Generating certificate for client: $CLIENT_NAME"
    ./easyrsa --batch build-client-full "$CLIENT_NAME" nopass

    log "Certificate for $CLIENT_NAME generated successfully"
}

revoke_client_cert() {
    local CLIENT_NAME="$1"

    if [ -z "$CLIENT_NAME" ]; then
	error "Client name not provided"
	return 1
    fi

    cd "$EASYRSA_DIR"

    if [ ! -f "pki/issued/${CLIENT_NAME}.crt" ]; then
	error "Client '$CLIENT_NAME' does not exist"
	return 1
    fi

    log "Revoking certificate for client: $CLIENT_NAME"
    ./easyrsa --batch revoke "$CLIENT_NAME"
    ./easyrsa gen-crl

    cd "$EASYRSA_DIR/pki/crl.pem" "$OPENVPN_DIR/"

    rm -f "$CLIENT_DIR/${CLIENT_NAME}.ovpn"

    systemctl restart openvpn@server

    log "Certificate for $CLIENT_NAME revoked successfully"
}

generate_server_config() {
    local PORT="$1"
    local PROTOCOL="$2"
    local SUBNET="$3"
    local DNS="$4"

    log "Generating server configuration"

    cat > "$OPENVPN_DIR/server.conf" << EOF
# OpenVPN server config
# Generated by https://github.com/bashcrumb/openvpn-setup/setup.sh

port $PORT
proto $PROTOCOL
dev tun

# certs & keys
ca ca.cert
cert server.crt
key server.key
dh dh.pem
tls-crypt ta.key

# network config
server $SUBNET 255.255.255.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS $DNS"

# security
cipher AES-256-GCM
auth SHA256
tls-version-min 1.2

# performance and reliability
keepalive 10 120
persist-key
persist-tun

# privs
user nobody
group $([ "$DISTRO" = "arch" ] && echo "nobody" || echo "nogroup")

# logging
status /var/log/openvpn-status.log
log-append /var/log/openvpn.log
verb 3

crl-verify crl.pem

compress lzo
push "compress lzo"

max-clients 100

explicit-exit-notify 1
EOF

    log "Server configuration generated at $OPENVPN_DIR/server.conf"
}

setup_networking() {
    local INTERFACE="$1"

    log "Configuration network settings"

    echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/99-openvpn.conf
    sysctl -p /etc/sysctl.d/99-openvpn.conf

    if command -v nft &> /dev/null && nft list tables 2>/dev/null | grep -q .; then
	FIREWALL="nftables"
	setup_nftables "$INTERFACE"
    else
	FIREWALL="iptables"
	setup_iptables "$INTERFACE"
    fi

    log "Network configuration complete (using $FIREWALL)"
}

setup_iptables() {
    local INTERFACE="$1"

    log "Configuration iptables"

    iptables -t nat -A POSTROUTING -s $DEFAULT_SUBNET/24 -o "$INTERFACE" -j MASQUERADE

    if [ "$DISTRO" = "debian" ]; then
	if ! dpkg -l | grep -q iptables-persistent; then
	    DEBIAN_FRONTEND=noninteractive apt-get install -y iptables-persistent
	fi
	netfilter-persistent save
    elif [ "$DISTRO" = "arch" ]; then
	iptables-save > /etc/iptables/iptables.rules
	systemctl enable iptables
    fi
}

setup_nftables() {
    local INTERFACE="$1"

    log "Configuration nftables"

    cat > /etc/nftables.d/openvpn.nft << EOF
table ip openvpn {
    chain postrouting {
	type nat hook postrouting priority srcnat;
	oifname "$INTERFACE" ip saddr $DEFAULT_SUBNET/24 masquerade
    }
}
EOF

    nft -f /etc/nftables.d/openvpn.nft

    if [ "$DISTRO" = "debian" ]; then
	systemctl enable nftables
    fi
}

generate_client_config() {
    local CLIENT_NAME="$1"
    local SERVER_IP="$2"
    local PORT="$3"
    local PROTOCOL="$4"
    local GENERATE_QR="${5:-false}"

    log "Generating client configuration for: $CLIENT_NAME"

    CA_CERT=$(cat "$OPENVPN_DIR/ca.crt")
    CLIENT_CERT=$(cat "$EASYRSA_DIR/pki/issues/${CLIENT_NAME}.crt")
    CLIENT_KEY=$(cat "$EASYRSA_DIR/pki/private/${CLIENT_NAME}.key")
    TA_KEY=$(cat "$OPENVPN_DIR/ta.key")

    cat > "$CLIENT_DIR/${CLIENT_NAME}.ovpn" << EOF
client
dev tun
proto $PROTOCOL
remote $SERVER_IP $PORT
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
cipher AES-256-GCM
auth SHA256
verb 3

<ca>
$CA_CERT
</ca>

<cert>
$CLIENT_CERT
</cert>

<key>
$CLIENT_KEY
</key>

<tls-crypt>
$TA_KEY
</tls-crypt>
EOF

    log "Client configuration saved to: $CLIENT_DIR/${CLIENT_NAME}.ovpn"

    if [ "$GENERATE_QR" = true ]; then
	qrencode -t ANSIUTF8 < "$CLIENT_DIR/${CLIENT_NAME}.ovpn"
        qrencode -t PNG -o "$CLIENT_DIR/${CLIENT_NAME}.png" < "$CLIENT_DIR/${CLIENT_NAME}.ovpn"
        log "QR code generated: $CLIENT_DIR/${CLIENT_NAME}.png"
    fi
}

enable_openvpn_service() {
    log "Enabling OpenVPN service"

    systemctl enable openvpn@server
    systemctl start openvpn@server

    if systemctl is-active --quiet openvpn@server; then
	log "OpenVPN service is running"
    else
	error "Failed to start OpenVPN service"
	journalctl -u openvpn@server --no-pager -n 20
	exit 1
    fi
}

interactive_setup() {
    echo "OpenVPN setup"

    read -p "Server port [default: $DEFAULT_PORT]: " PORT
    PORT=${PORT:-$DEFAULT_PORT}

    read -p "Protocol (udp/tcp) [default: $DEFAULT_PROTOCOL]: " PROTOCOL
    PROTOCOL=${PROTOCOL:-$DEFAULT_PROTOCOL}

    read -p "VPN subnet [default: $DEFAULT_SUBNET]: " SUBNET
    SUBNET=${SUBNET:-$DEFAULT_SUBNET}

    read -p "DNS server [default: $DEFAULT_DNS]: " DNS
    DNS=${DNS:-$DEFAULT_DNS}

    echo ""
    log "Configuration:"
    log "  Port: $PORT"
    log "  Protocol: $PROTOCOL"
    log "  Subnet: $SUBNET/24"
    log "  DNS: $DNS"
    echo ""

    read -p "Proceed with installation? (y/n): " CONFIRM
    if [ "$CONFIRM" != "y" ]; then
	log "Installation cancelled"
	exit 0
    fi

    install_dependencies
    init_pki

    INTERFACE=$(detect_network_interface)
    PUBLIC_IP=$(get_public_ip)

    generate_server_config "$PORT" "$PROTOCOL" "$SUBNET" "$DNS"
    setup_networking "$INTERFACE"
    enable_openvpn_service

    echo ""
    log "OpenVPN server installation complete!"
    log "Server is listening on $PUBLIC_IP:$PORT ($PROTOCOL)"
    echo ""
    log "Next steps:"
    log "  1. Add a client: $0 add-client <name>"
    log "  2. Check status: $0 status"
    echo ""
}

cmd_init() {
    check_root
    detect_distro
    
    # Check if already installed
    if systemctl is-active --quiet openvpn@server 2>/dev/null; then
        warning "OpenVPN server is already running"
        read -p "Reinstall? This will backup existing configuration. (y/n): " CONFIRM
        if [ "$CONFIRM" != "y" ]; then
            exit 0
        fi
        
        # Backup existing configuration
        BACKUP_DIR="/etc/openvpn/backup-$(date +%Y%m%d-%H%M%S)"
        mkdir -p "$BACKUP_DIR"
        cp -r "$OPENVPN_DIR"/* "$BACKUP_DIR/" 2>/dev/null || true
        log "Existing configuration backed up to: $BACKUP_DIR"
    fi
    
    interactive_setup
}

cmd_add_client() {
    local CLIENT_NAME="$1"
    local GENERATE_QR=false
    
    if [ -z "$CLIENT_NAME" ]; then
        error "Usage: $0 add-client <client-name> [--mobile]"
        exit 1
    fi
    
    # Check for --mobile flag
    if [ "$2" = "--mobile" ]; then
        GENERATE_QR=true
    fi
    
    check_root
    detect_distro
    
    # Get server configuration
    if [ ! -f "$OPENVPN_DIR/server.conf" ]; then
        error "OpenVPN server not configured. Run: $0 init"
        exit 1
    fi
    
    PORT=$(grep "^port" "$OPENVPN_DIR/server.conf" | awk '{print $2}')
    PROTOCOL=$(grep "^proto" "$OPENVPN_DIR/server.conf" | awk '{print $2}')
    PUBLIC_IP=$(get_public_ip)
    
    generate_client_cert "$CLIENT_NAME"
    generate_client_config "$CLIENT_NAME" "$PUBLIC_IP" "$PORT" "$PROTOCOL" "$GENERATE_QR"
    
    echo ""
    log "✓ Client configuration created: $CLIENT_DIR/${CLIENT_NAME}.ovpn"
    if [ "$GENERATE_QR" = true ]; then
        log "✓ QR code: $CLIENT_DIR/${CLIENT_NAME}.png"
    fi
    echo ""
}

cmd_revoke_client() {
    local CLIENT_NAME="$1"
    
    if [ -z "$CLIENT_NAME" ]; then
        error "Usage: $0 revoke-client <client-name>"
        exit 1
    fi
    
    check_root
    detect_distro
    
    read -p "Revoke client '$CLIENT_NAME'? (y/n): " CONFIRM
    if [ "$CONFIRM" != "y" ]; then
        exit 0
    fi
    
    revoke_client_cert "$CLIENT_NAME"
    
    log "✓ Client '$CLIENT_NAME' revoked"
}

cmd_status() {
    check_root

    if ! systemctl is-active --quiet openvpn@server; then
	error "OpenVPN server not running"
	exit 1
    fi

    echo "OpenVPN server status:"
    log "Service status:"
    systemctl status openvpn@server --no-pager -l

    echo ""
    log "Connected clients:"
    if [ -f /var/log/openvpn-status.log ]; then
	cat /var/log/openvpn-status.log
    else
	log "No clients connected"
    fi
    echo ""
}

cmd_list_clients() {
    check_root
    detect_distro

    cd "$EASYRSA_DIR"

    echo "Client certificates"

    if [ -d "pki/issued" ]; then
	for cert in pki/issued/*.crt; do
	    if [ -f "$cert" ]; then
		CLIENT=$(basename "$cert" .crt)
		if [ "$CLIENT" != "server" ]; then
		    echo "   - $CLIENT"
		fi
	    fi
	done
    else
	log "No clients found"
    fi
    echo ""
}

show_usage() {
    cat << EOF
OpenVPN Easy Setup Script

USAGE:
    $0 <command> [options]

COMMANDS:
    init                    Initialize and configure OpenVPN server
    add-client <name>       Generate client configuration
    add-client <name> --mobile   Generate client config with QR code
    revoke-client <name>    Revoke a client certificate
    list-clients            List all client certificates
    status                  Show server status and connected clients
    help                    Show this help message

EXAMPLES:
    $0 init
    $0 add-client laptop
    $0 add-client phone --mobile
    $0 revoke-client old-laptop
    $0 status

EOF
}

main() {
    local COMMAND="$1"
    shift || true
    
    case "$COMMAND" in
        init)
            cmd_init "$@"
            ;;
        add-client)
            cmd_add_client "$@"
            ;;
        revoke-client)
            cmd_revoke_client "$@"
            ;;
        list-clients)
            cmd_list_clients
            ;;
        status)
            cmd_status
            ;;
        help|--help|-h)
            show_usage
            ;;
        *)
            error "Unknown command: $COMMAND"
            show_usage
            exit 1
            ;;
    esac
}

main "$@"
